var fs = require('fs');
var path = require('path');
var landingPath = path.join('client', 'src', 'components', 'LandingPage.jsx');
var landing = fs.readFileSync(landingPath, 'utf8');
var c = 0;
var b;
b=landing; landing = landing.replace('className="text-3xl sm:text-4xl font-serif text-white leading-tight tracking-tight"','className="text-4xl sm:text-6xl font-serif text-white leading-[1.1] tracking-tight"'); if(landing!==b){c++;console.log('1. Hero title - MUCH bigger');}
b=landing; landing = landing.replace('className="text-gray-500 text-sm sm:text-base font-light leading-relaxed max-w-xs mx-auto"','className="text-gray-400 text-base sm:text-lg font-light leading-relaxed max-w-sm mx-auto"'); if(landing!==b){c++;console.log('2. Hero subtitle - bigger');}
b=landing; landing = landing.replace('className="w-16 h-16 rounded-2xl bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center mx-auto shadow-lg shadow-emerald-500/10"','className="w-20 h-20 rounded-3xl bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center mx-auto shadow-xl shadow-emerald-500/20"'); if(landing!==b){c++;console.log('3. Hero icon - bigger');}
b=landing; landing = landing.replace("You don't have to go<br />through today alone","You don't have to go<br /><span className=\"bg-gradient-to-r from-emerald-300 via-emerald-400 to-teal-400 bg-clip-text text-transparent\">through today alone</span>"); if(landing!==b){c++;console.log('4. Hero gradient glow added');}
b=landing; landing = landing.replace('className="text-[15px] font-medium text-white group-hover:text-emerald-300 transition-colors">I need someone today','className="text-base sm:text-lg font-semibold text-white group-hover:text-emerald-300 transition-colors">I need someone today'); if(landing!==b){c++;console.log('5. CTA need someone - bigger');}
b=landing; landing = landing.replace('className="text-gray-500 text-xs mt-0.5 font-light">Be matched with someone who is here to listen','className="text-gray-400 text-sm mt-1 font-light">Be matched with someone who is here to listen'); if(landing!==b){c++;console.log('6. CTA subtext 1 - bigger');}
b=landing; landing = landing.replace('className="text-[15px] font-medium text-white group-hover:text-emerald-300 transition-colors">I can be someone today','className="text-base sm:text-lg font-semibold text-white group-hover:text-emerald-300 transition-colors">I can be someone today'); if(landing!==b){c++;console.log('7. CTA be someone - bigger');}
b=landing; landing = landing.replace('className="text-gray-500 text-xs mt-0.5 font-light">Be there for someone who needs a quiet presence','className="text-gray-400 text-sm mt-1 font-light">Be there for someone who needs a quiet presence'); if(landing!==b){c++;console.log('8. CTA subtext 2 - bigger');}
b=landing; landing = landing.replace(/className="text-xs text-gray-600 font-light">Private/g, 'className="text-sm text-gray-400 font-light">Private'); if(landing!==b){c++;console.log('9. Badge Private - bigger');}
b=landing; landing = landing.replace(/className="text-xs text-gray-600 font-light">15-30 min/g, 'className="text-sm text-gray-400 font-light">15-30 min'); if(landing!==b){c++;console.log('10. Badge 15-30 - bigger');}
b=landing; landing = landing.replace(/className="text-xs text-gray-600 font-light">Nothing saved/g, 'className="text-sm text-gray-400 font-light">Nothing saved'); if(landing!==b){c++;console.log('11. Badge Nothing saved - bigger');}
b=landing; landing = landing.replace(/className="w-3\.5 h-3\.5 text-gray-600"/g, 'className="w-4 h-4 text-gray-400"'); if(landing!==b){c++;console.log('12. Badge icons - bigger');}
b=landing; landing = landing.replace('className="text-2xl sm:text-3xl font-serif text-white">How it works','className="text-3xl sm:text-5xl font-serif text-white">How it works'); if(landing!==b){c++;console.log('13. How it works heading - bigger');}
b=landing; landing = landing.replace('className="text-gray-500 text-sm font-light max-w-md mx-auto">Three simple steps','className="text-gray-400 text-base font-light max-w-md mx-auto">Three simple steps'); if(landing!==b){c++;console.log('14. How it works subtitle - bigger');}
b=landing; landing = landing.replace('className="text-white font-medium text-sm">Choose your role','className="text-white font-semibold text-lg">Choose your role'); if(landing!==b){c++;console.log('15. Step 1 title - bigger');}
b=landing; landing = landing.replace('className="text-white font-medium text-sm">Get matched instantly','className="text-white font-semibold text-lg">Get matched instantly'); if(landing!==b){c++;console.log('16. Step 2 title - bigger');}
b=landing; landing = landing.replace("className=\"text-white font-medium text-sm\">Talk. That's it.","className=\"text-white font-semibold text-lg\">Talk. That's it."); if(landing!==b){c++;console.log('17. Step 3 title - bigger');}
b=landing; landing = landing.replace("className=\"text-gray-500 text-xs font-light leading-relaxed\">Need to talk? Or want to listen? Pick what feels right for you today.","className=\"text-gray-400 text-sm font-light leading-relaxed\">Need to talk? Or want to listen? Pick what feels right for you today."); if(landing!==b){c++;console.log('18. Step 1 body - bigger');}
b=landing; landing = landing.replace("className=\"text-gray-500 text-xs font-light leading-relaxed\">We connect you with a real person in seconds. No profiles, no waiting rooms.","className=\"text-gray-400 text-sm font-light leading-relaxed\">We connect you with a real person in seconds. No profiles, no waiting rooms."); if(landing!==b){c++;console.log('19. Step 2 body - bigger');}
b=landing; landing = landing.replace("className=\"text-gray-500 text-xs font-light leading-relaxed\">Have a real conversation. When the session ends, everything disappears. Nothing is saved.","className=\"text-gray-400 text-sm font-light leading-relaxed\">Have a real conversation. When the session ends, everything disappears. Nothing is saved."); if(landing!==b){c++;console.log('20. Step 3 body - bigger');}
b=landing; landing = landing.replace('className="text-2xl sm:text-3xl font-serif text-white">Built different','className="text-3xl sm:text-5xl font-serif text-white">Built different'); if(landing!==b){c++;console.log('21. Built different heading - bigger');}
b=landing; landing = landing.replace("className=\"text-gray-500 text-sm font-light max-w-md mx-auto\">We're not a social network","className=\"text-gray-400 text-base font-light max-w-md mx-auto\">We're not a social network"); if(landing!==b){c++;console.log('22. Built different subtitle - bigger');}
b=landing; landing = landing.replace('className="text-white font-medium text-sm">Completely anonymous','className="text-white font-semibold text-base">Completely anonymous'); if(landing!==b){c++;console.log('23. Anonymous title - bigger');}
b=landing; landing = landing.replace('className="text-white font-medium text-sm">Nothing is saved','className="text-white font-semibold text-base">Nothing is saved'); if(landing!==b){c++;console.log('24. Nothing saved title - bigger');}
b=landing; landing = landing.replace('className="text-white font-medium text-sm">Human-first design','className="text-white font-semibold text-base">Human-first design'); if(landing!==b){c++;console.log('25. Human-first title - bigger');}
b=landing; landing = landing.replace('className="text-white font-medium text-sm">Safe space','className="text-white font-semibold text-base">Safe space'); if(landing!==b){c++;console.log('26. Safe space title - bigger');}
b=landing; landing = landing.replace('className="text-gray-500 text-xs font-light leading-relaxed">No accounts. No names. No traces.','className="text-gray-400 text-sm font-light leading-relaxed">No accounts. No names. No traces.'); if(landing!==b){c++;console.log('27. Anonymous body - bigger');}
b=landing; landing = landing.replace("className=\"text-gray-500 text-xs font-light leading-relaxed\">Conversations exist only in the moment.","className=\"text-gray-400 text-sm font-light leading-relaxed\">Conversations exist only in the moment."); if(landing!==b){c++;console.log('28. Nothing saved body - bigger');}
b=landing; landing = landing.replace('className="text-gray-500 text-xs font-light leading-relaxed">No algorithms deciding who you talk to.','className="text-gray-400 text-sm font-light leading-relaxed">No algorithms deciding who you talk to.'); if(landing!==b){c++;console.log('29. Human-first body - bigger');}
b=landing; landing = landing.replace('className="text-gray-500 text-xs font-light leading-relaxed">Community-driven guidelines,','className="text-gray-400 text-sm font-light leading-relaxed">Community-driven guidelines,'); if(landing!==b){c++;console.log('30. Safe space body - bigger');}
b=landing; landing = landing.replace('className="text-2xl sm:text-3xl font-serif text-white">On the horizon','className="text-3xl sm:text-5xl font-serif text-white">On the horizon'); if(landing!==b){c++;console.log('31. On the horizon heading - bigger');}
b=landing; landing = landing.replace("className=\"text-gray-500 text-sm font-light max-w-md mx-auto\">We're just getting started.","className=\"text-gray-400 text-base font-light max-w-md mx-auto\">We're just getting started."); if(landing!==b){c++;console.log('32. On horizon subtitle - bigger');}
b=landing; landing = landing.replace('className="text-white font-medium text-sm">Voice sessions','className="text-white font-semibold text-base">Voice sessions'); if(landing!==b){c++;console.log('33. Voice title - bigger');}
b=landing; landing = landing.replace('className="text-white font-medium text-sm">Multi-language','className="text-white font-semibold text-base">Multi-language'); if(landing!==b){c++;console.log('34. Language title - bigger');}
b=landing; landing = landing.replace('className="text-white font-medium text-sm">Listener recognition','className="text-white font-semibold text-base">Listener recognition'); if(landing!==b){c++;console.log('35. Recognition title - bigger');}
b=landing; landing = landing.replace('className="text-white font-medium text-sm">Mobile app','className="text-white font-semibold text-base">Mobile app'); if(landing!==b){c++;console.log('36. Mobile title - bigger');}
b=landing; landing = landing.replace("className=\"text-gray-500 text-xs font-light leading-relaxed\">Sometimes typing isn't enough.","className=\"text-gray-400 text-sm font-light leading-relaxed\">Sometimes typing isn't enough."); if(landing!==b){c++;console.log('37. Voice body - bigger');}
b=landing; landing = landing.replace('className="text-gray-500 text-xs font-light leading-relaxed">Support in multiple languages','className="text-gray-400 text-sm font-light leading-relaxed">Support in multiple languages'); if(landing!==b){c++;console.log('38. Language body - bigger');}
b=landing; landing = landing.replace('className="text-gray-500 text-xs font-light leading-relaxed">Anonymous badges and milestones','className="text-gray-400 text-sm font-light leading-relaxed">Anonymous badges and milestones'); if(landing!==b){c++;console.log('39. Recognition body - bigger');}
b=landing; landing = landing.replace("className=\"text-gray-500 text-xs font-light leading-relaxed\">A dedicated app so you can be here","className=\"text-gray-400 text-sm font-light leading-relaxed\">A dedicated app so you can be here"); if(landing!==b){c++;console.log('40. Mobile body - bigger');}
b=landing; landing = landing.replace('className="text-2xl sm:text-3xl font-serif text-white">Ready to talk to someone?','className="text-3xl sm:text-5xl font-serif text-white">Ready to talk to someone?'); if(landing!==b){c++;console.log('41. Final CTA heading - bigger');}
b=landing; landing = landing.replace('className="text-gray-500 text-sm font-light">It takes 10 seconds to connect.','className="text-gray-400 text-base font-light">It takes 10 seconds to connect.'); if(landing!==b){c++;console.log('42. Final CTA subtitle - bigger');}
b=landing; landing = landing.replace('className="text-gray-500 text-xs font-light leading-relaxed text-center"','className="text-gray-400 text-sm font-light leading-relaxed text-center"'); if(landing!==b){c++;console.log('43. Crisis banner - bigger');}
b=landing; landing = landing.replace('className="text-center text-gray-700 text-[11px] font-light"','className="text-center text-gray-600 text-xs font-light"'); if(landing!==b){c++;console.log('44. Copyright - bigger');}
b=landing; landing = landing.replace('className="text-2xl font-serif text-white">How are you feeling?','className="text-3xl sm:text-4xl font-serif text-white">How are you feeling?'); if(landing!==b){c++;console.log('45. Mood heading - bigger');}
b=landing; landing = landing.replace('className="text-gray-500 text-sm font-light">Select all that apply.','className="text-gray-400 text-base font-light">Select all that apply.'); if(landing!==b){c++;console.log('46. Mood subtitle - bigger');}
b=landing; landing = landing.replace('className="block text-2xl mb-1">{m.emoji}','className="block text-3xl mb-2">{m.emoji}'); if(landing!==b){c++;console.log('47. Mood emojis - bigger');}
b=landing; landing = landing.replace('className="text-2xl font-serif text-white">How long would you like to chat?','className="text-3xl sm:text-4xl font-serif text-white">How long would you like to chat?'); if(landing!==b){c++;console.log('48. Duration heading - bigger');}
b=landing; landing = landing.replace('className="text-gray-500 text-sm font-light">Pick a session length.','className="text-gray-400 text-base font-light">Pick a session length.'); if(landing!==b){c++;console.log('49. Duration subtitle - bigger');}
b=landing; landing = landing.replace('className="text-gray-600 text-xs font-light">Nothing is recorded.','className="text-gray-500 text-sm font-light">Nothing is recorded.'); if(landing!==b){c++;console.log('50. Duration note - bigger');}
b=landing; landing = landing.replace('className="text-center text-xs sm:text-sm font-light text-emerald-300"','className="text-center text-sm sm:text-base font-light text-emerald-300"'); if(landing!==b){c++;console.log('51. Launch banner - bigger');}
b=landing; landing = landing.replace('className="text-emerald-400/70 text-xs font-light"','className="text-emerald-400/80 text-sm font-light"'); if(landing!==b){c++;console.log('52. Active count - bigger');}
fs.writeFileSync(landingPath, landing);
console.log(c + ' changes applied');
console.log('ALL DONE');
