var fs = require('fs');
console.log('Upgrading Letters UI...\n');

fs.writeFileSync('client/src/components/LetterWall.jsx', [
'import { useState, useEffect } from "react";',
'import WriteLetter from "./WriteLetter";',
'import LetterDetail from "./LetterDetail";',
'',
'var tagEmojis = { all: "\\u2728", lonely: "\\uD83C\\uDF19", anxious: "\\u26A1", sad: "\\uD83C\\uDF27\\uFE0F", lost: "\\uD83C\\uDF0D", overwhelmed: "\\uD83C\\uDF0A", angry: "\\uD83D\\uDD25", numb: "\\uD83E\\uDDCA", grateful: "\\uD83D\\uDE4F", hopeful: "\\uD83C\\uDF31", healing: "\\uD83E\\uDE77" };',
'',
'export default function LetterWall({ onBack }) {',
'  var [letters, setLetters] = useState([]);',
'  var [loading, setLoading] = useState(true);',
'  var [activeTag, setActiveTag] = useState("all");',
'  var [view, setView] = useState("wall");',
'  var [selectedLetter, setSelectedLetter] = useState(null);',
'  var [writeType, setWriteType] = useState("letter");',
'  var [page, setPage] = useState(0);',
'  var [hasMore, setHasMore] = useState(false);',
'  var tags = ["all","lonely","anxious","sad","lost","overwhelmed","angry","numb","grateful","hopeful","healing"];',
'',
'  function fetchLetters(tagFilter, pageNum) {',
'    setLoading(true);',
'    var url = "/api/letters?page=" + (pageNum || 0);',
'    if (tagFilter && tagFilter !== "all") url += "&tag=" + tagFilter;',
'    fetch(url).then(function(r) { return r.json(); }).then(function(data) {',
'      if (pageNum > 0) { setLetters(function(prev) { return prev.concat(data.letters); }); }',
'      else { setLetters(data.letters); }',
'      setHasMore(data.hasMore); setLoading(false);',
'    }).catch(function() { setLoading(false); });',
'  }',
'',
'  useEffect(function() { fetchLetters(activeTag, 0); setPage(0); }, [activeTag]);',
'',
'  function handleHeart(letterId, e) {',
'    e.stopPropagation();',
'    var btn = e.currentTarget;',
'    btn.style.transform = "scale(1.4)";',
'    setTimeout(function() { btn.style.transform = "scale(1)"; }, 300);',
'    fetch("/api/letters/" + letterId + "/heart", { method: "POST" }).then(function(r) { return r.json(); }).then(function(data) {',
'      setLetters(function(prev) { return prev.map(function(l) { if (l.id === letterId) return Object.assign({}, l, { hearts: data.hearts }); return l; }); });',
'    });',
'  }',
'',
'  function timeAgo(ts) {',
'    var diff = Date.now() - ts; var mins = Math.floor(diff / 60000);',
'    if (mins < 1) return "just now"; if (mins < 60) return mins + "m ago";',
'    var hrs = Math.floor(mins / 60); if (hrs < 24) return hrs + "h ago";',
'    return Math.floor(hrs / 24) + "d ago";',
'  }',
'',
'  if (view === "write") return <WriteLetter type={writeType} onBack={function() { setView("wall"); }} onPosted={function() { setView("wall"); fetchLetters(activeTag, 0); setPage(0); }} />;',
'  if (view === "detail" && selectedLetter) return <LetterDetail letterId={selectedLetter} onBack={function() { setView("wall"); fetchLetters(activeTag, 0); }} />;',
'',
'  return (',
'    <div className="min-h-screen bg-[#0a0a0f] relative overflow-hidden">',
'      <style>{`',
'        @keyframes fadeInUp { from { opacity: 0; transform: translateY(24px); } to { opacity: 1; transform: translateY(0); } }',
'        @keyframes float { 0%, 100% { transform: translateY(0); opacity: 0.3; } 50% { transform: translateY(-20px); opacity: 0.6; } }',
'        .letter-card { animation: fadeInUp 0.6s ease-out both; }',
'        .letter-card:hover { transform: translateY(-2px); box-shadow: 0 8px 32px rgba(16, 185, 129, 0.08); }',
'        .floating-dot { animation: float linear infinite; position: absolute; border-radius: 50%; pointer-events: none; }',
'        .heart-btn { transition: transform 0.3s cubic-bezier(0.175, 0.885, 0.32, 1.275); }',
'        .heart-btn:hover { transform: scale(1.2); }',
'        .write-btn:hover { transform: translateY(-2px); box-shadow: 0 8px 24px rgba(0,0,0,0.2); }',
'        .scrollbar-hide::-webkit-scrollbar { display: none; }',
'      `}</style>',
'',
'      <div className="absolute inset-0 overflow-hidden pointer-events-none">',
'        <div className="floating-dot bg-emerald-400/20 w-1 h-1" style={{top:"10%",left:"15%",animationDuration:"8s"}}></div>',
'        <div className="floating-dot bg-emerald-400/20 w-1.5 h-1.5" style={{top:"25%",right:"20%",animationDuration:"12s",animationDelay:"2s"}}></div>',
'        <div className="floating-dot bg-amber-400/20 w-1 h-1" style={{top:"60%",left:"80%",animationDuration:"10s",animationDelay:"4s"}}></div>',
'        <div className="floating-dot bg-emerald-400/10 w-2 h-2" style={{top:"75%",left:"10%",animationDuration:"14s"}}></div>',
'      </div>',
'',
'      <div className="px-5 py-8 relative z-10">',
'        <div className="max-w-2xl mx-auto">',
'          <div className="flex items-center justify-between mb-6">',
'            <button onClick={onBack} className="text-gray-500 hover:text-white transition-colors text-sm flex items-center gap-1">',
'              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M15 19l-7-7 7-7" /></svg>',
'              Back',
'            </button>',
'            <div className="text-center">',
'              <h1 className="text-2xl sm:text-3xl font-serif text-white tracking-wide">Letters</h1>',
'              <div className="w-12 h-0.5 bg-gradient-to-r from-transparent via-emerald-500/50 to-transparent mx-auto mt-2"></div>',
'            </div>',
'            <div className="w-14"></div>',
'          </div>',
'',
'          <p className="text-gray-400/80 text-center text-sm font-light mb-8 leading-relaxed font-serif italic">',
'            Write what\\\'s on your heart. No names, no judgment.<br />',
'            <span className="text-emerald-400/50">Someone will read this.</span>',
'          </p>',
'',
'          <div className="flex gap-3 mb-8">',
'            <button onClick={function() { setWriteType("letter"); setView("write"); }} className="write-btn flex-1 bg-white/[0.03] hover:bg-white/[0.07] border border-white/[0.08] hover:border-emerald-500/20 rounded-2xl py-4 px-5 text-left group transition-all">',
'              <div className="flex items-center gap-3">',
'                <span className="text-xl opacity-70 group-hover:opacity-100 transition-opacity">{"\\u2709\\uFE0F"}</span>',
'                <div>',
'                  <span className="text-white text-sm font-medium">Write a letter</span>',
'                  <p className="text-gray-500 text-xs mt-0.5">Share what\\\'s on your mind</p>',
'                </div>',
'              </div>',
'            </button>',
'            <button onClick={function() { setWriteType("light"); setView("write"); }} className="write-btn flex-1 bg-amber-500/[0.03] hover:bg-amber-500/[0.08] border border-amber-500/[0.1] hover:border-amber-500/25 rounded-2xl py-4 px-5 text-left group transition-all">',
'              <div className="flex items-center gap-3">',
'                <span className="text-xl opacity-70 group-hover:opacity-100 transition-opacity">{"\\u2728"}</span>',
'                <div>',
'                  <span className="text-amber-300 text-sm font-medium">Share some light</span>',
'                  <p className="text-amber-400/40 text-xs mt-0.5">Spread positivity</p>',
'                </div>',
'              </div>',
'            </button>',
'          </div>',
'',
'          <div className="flex gap-2 overflow-x-auto pb-4 mb-6 scrollbar-hide">',
'            {tags.map(function(tag) {',
'              var emoji = tagEmojis[tag] || "";',
'              return (',
'                <button key={tag} onClick={function() { setActiveTag(tag); }} className={"whitespace-nowrap px-3.5 py-2 rounded-full text-xs transition-all duration-200 flex items-center gap-1.5 " + (activeTag === tag ? "bg-emerald-500/20 text-emerald-300 border border-emerald-500/30 shadow-lg shadow-emerald-500/10" : "bg-white/[0.03] text-gray-500 border border-white/[0.06] hover:bg-white/[0.06] hover:text-gray-300")}>',
'                  <span>{emoji}</span><span>{tag}</span>',
'                </button>',
'              );',
'            })}',
'          </div>',
'',
'          {loading && letters.length === 0 ? (',
'            <div className="text-center py-20">',
'              <div className="inline-flex items-center gap-2 text-gray-500 text-sm">',
'                <svg className="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"></path></svg>',
'                Loading letters...',
'              </div>',
'            </div>',
'          ) : letters.length === 0 ? (',
'            <div className="text-center py-20">',
'              <div className="text-4xl mb-4 opacity-30">{"\\u2709\\uFE0F"}</div>',
'              <p className="text-gray-500 text-sm mb-6 font-light">No letters yet. Be the first.</p>',
'              <button onClick={function() { setWriteType("letter"); setView("write"); }} className="bg-emerald-500/15 text-emerald-400 border border-emerald-500/25 rounded-full px-8 py-3 text-sm hover:bg-emerald-500/25 transition-all">Write the first letter</button>',
'            </div>',
'          ) : (',
'            <div className="space-y-4">',
'              {letters.map(function(letter, index) {',
'                var isLight = letter.type === "light";',
'                return (',
'                  <div key={letter.id} onClick={function() { setSelectedLetter(letter.id); setView("detail"); }}',
'                    className={"letter-card rounded-2xl p-5 sm:p-6 cursor-pointer transition-all duration-300 " + (isLight ? "bg-gradient-to-br from-amber-500/[0.04] to-amber-600/[0.02] border border-amber-500/[0.12] hover:border-amber-500/25" : "bg-gradient-to-br from-white/[0.03] to-white/[0.01] border border-white/[0.06] hover:border-emerald-500/20")}',
'                    style={{animationDelay: (index * 0.08) + "s"}}',
'                  >',
'                    {isLight && <div className="flex items-center gap-2 mb-3"><span className="text-amber-400 text-xs">{"\\u2728"}</span><span className="text-amber-400/60 text-xs font-light tracking-wide uppercase">Wall of Light</span></div>}',
'                    <p className={"text-sm sm:text-base leading-relaxed mb-4 font-serif " + (isLight ? "text-amber-100/80" : "text-gray-300/90")}>{letter.text}</p>',
'                    {letter.tags && letter.tags.length > 0 && <div className="flex flex-wrap gap-1.5 mb-3">{letter.tags.map(function(tag) { return <span key={tag} className="text-[10px] text-emerald-400/50 bg-emerald-500/[0.06] px-2.5 py-1 rounded-full flex items-center gap-1"><span>{tagEmojis[tag] || ""}</span> {tag}</span>; })}</div>}',
'                    <div className="flex items-center justify-between pt-2 border-t border-white/[0.04]">',
'                      <span className="text-gray-600 text-xs">{timeAgo(letter.createdAt)}</span>',
'                      <div className="flex items-center gap-4">',
'                        <button onClick={function(e) { handleHeart(letter.id, e); }} className="heart-btn flex items-center gap-1.5 text-gray-500 hover:text-rose-400 transition-colors"><span className="text-sm">{"\\u2665"}</span><span className="text-xs">{letter.hearts || 0}</span></button>',
'                        <div className="flex items-center gap-1.5 text-gray-600"><span className="text-xs">{"\\uD83D\\uDCAC"}</span><span className="text-xs">{letter.replyCount || 0}</span></div>',
'                      </div>',
'                    </div>',
'                  </div>',
'                );',
'              })}',
'              {hasMore && <button onClick={function() { var n = page + 1; setPage(n); fetchLetters(activeTag, n); }} className="w-full text-center py-4 text-gray-500 hover:text-emerald-400 text-sm transition-colors">Load more letters...</button>}',
'            </div>',
'          )}',
'        </div>',
'      </div>',
'    </div>',
'  );',
'}'
].join('\n'));
console.log('1/3 LetterWall.jsx upgraded');

fs.writeFileSync('client/src/components/WriteLetter.jsx', [
'import { useState, useEffect } from "react";',
'',
'var tagData = {',
'  lonely: { emoji: "\\uD83C\\uDF19", label: "lonely" },',
'  anxious: { emoji: "\\u26A1", label: "anxious" },',
'  sad: { emoji: "\\uD83C\\uDF27\\uFE0F", label: "sad" },',
'  lost: { emoji: "\\uD83C\\uDF0D", label: "lost" },',
'  overwhelmed: { emoji: "\\uD83C\\uDF0A", label: "overwhelmed" },',
'  angry: { emoji: "\\uD83D\\uDD25", label: "angry" },',
'  numb: { emoji: "\\uD83E\\uDDCA", label: "numb" },',
'  grateful: { emoji: "\\uD83D\\uDE4F", label: "grateful" },',
'  hopeful: { emoji: "\\uD83C\\uDF31", label: "hopeful" },',
'  healing: { emoji: "\\uD83E\\uDE77", label: "healing" }',
'};',
'',
'export default function WriteLetter({ type, onBack, onPosted }) {',
'  var [text, setText] = useState("");',
'  var [selectedTags, setSelectedTags] = useState([]);',
'  var [posting, setPosting] = useState(false);',
'  var [error, setError] = useState("");',
'  var [sent, setSent] = useState(false);',
'  var isLight = type === "light";',
'  var tagKeys = isLight ? ["grateful","hopeful","healing"] : Object.keys(tagData);',
'',
'  function toggleTag(tag) {',
'    setSelectedTags(function(prev) {',
'      if (prev.indexOf(tag) !== -1) return prev.filter(function(t) { return t !== tag; });',
'      if (prev.length >= 3) return prev;',
'      return prev.concat([tag]);',
'    });',
'  }',
'',
'  function handleSubmit() {',
'    if (text.trim().length < 10) { setError("Write at least 10 characters."); return; }',
'    setPosting(true); setError("");',
'    fetch("/api/letters", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ text: text.trim(), tags: selectedTags, type: type }) })',
'      .then(function(r) { return r.json(); })',
'      .then(function(data) {',
'        if (data.error) { setError(data.error); setPosting(false); }',
'        else { setSent(true); setTimeout(function() { onPosted(); }, 2500); }',
'      })',
'      .catch(function() { setError("Something went wrong."); setPosting(false); });',
'  }',
'',
'  if (sent) {',
'    return (',
'      <div className="min-h-screen bg-[#0a0a0f] flex items-center justify-center px-5">',
'        <style>{`',
'          @keyframes envelopeFly { 0% { transform: scale(1) translateY(0); opacity: 1; } 40% { transform: scale(1.1) translateY(-10px); } 100% { transform: scale(0.3) translateY(-200px); opacity: 0; } }',
'          @keyframes fadeInSlow { from { opacity: 0; transform: translateY(16px); } to { opacity: 1; transform: translateY(0); } }',
'          .envelope-fly { animation: envelopeFly 2s ease-in-out forwards; }',
'          .sent-text { animation: fadeInSlow 0.8s ease-out 1.2s both; }',
'        `}</style>',
'        <div className="text-center">',
'          <div className="envelope-fly text-6xl mb-8">{isLight ? "\\u2728" : "\\u2709\\uFE0F"}</div>',
'          <h2 className="sent-text text-xl font-serif text-white mb-3">{isLight ? "Your light is out there" : "Your letter has been sent"}</h2>',
'          <p className="sent-text text-gray-500 text-sm font-light" style={{animationDelay:"1.5s"}}>{isLight ? "Someone will feel warmer today" : "Someone will read this. You\\\'re not alone."}</p>',
'        </div>',
'      </div>',
'    );',
'  }',
'',
'  var charPercent = Math.min((text.length / 2000) * 100, 100);',
'',
'  return (',
'    <div className="min-h-screen bg-[#0a0a0f] px-5 py-8">',
'      <style>{`',
'        @keyframes fadeInUp { from { opacity: 0; transform: translateY(20px); } to { opacity: 1; transform: translateY(0); } }',
'        .fade-in { animation: fadeInUp 0.5s ease-out both; }',
'        .paper-area { background: linear-gradient(180deg, rgba(255,255,255,0.02) 0%, rgba(255,255,255,0.01) 100%); }',
'        .paper-area:focus { box-shadow: 0 0 40px rgba(16, 185, 129, 0.05); }',
'        .char-ring { transition: stroke-dashoffset 0.3s ease; }',
'      `}</style>',
'      <div className="max-w-xl mx-auto">',
'        <div className="fade-in flex items-center justify-between mb-8">',
'          <button onClick={onBack} className="text-gray-500 hover:text-white transition-colors text-sm flex items-center gap-1">',
'            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M15 19l-7-7 7-7" /></svg>',
'            Back',
'          </button>',
'          <div className="text-center">',
'            <h1 className={"text-xl font-serif " + (isLight ? "text-amber-300" : "text-white")}>{isLight ? "\\u2728 Share some light" : "\\u2709\\uFE0F Write a letter"}</h1>',
'            <div className={"w-8 h-0.5 mx-auto mt-2 " + (isLight ? "bg-amber-500/30" : "bg-emerald-500/30")}></div>',
'          </div>',
'          <div className="w-14"></div>',
'        </div>',
'',
'        <p className="fade-in text-gray-400/70 text-center text-sm font-light mb-8 font-serif italic" style={{animationDelay:"0.1s"}}>{isLight ? "Share a win, a moment of gratitude, or something that made you smile." : "Say what you need to say. It\\\'s anonymous. Someone will read this."}</p>',
'',
'        <div className="fade-in relative mb-2" style={{animationDelay:"0.15s"}}>',
'          <textarea value={text} onChange={function(e) { setText(e.target.value); }} placeholder={isLight ? "Something good happened today..." : "Dear someone..."} maxLength={2000} rows={10}',
'            className={"paper-area w-full border rounded-2xl px-6 py-5 text-white text-sm sm:text-base leading-relaxed placeholder-gray-600/50 focus:outline-none resize-none font-serif transition-all duration-300 " + (isLight ? "border-amber-500/[0.12] focus:border-amber-500/25" : "border-white/[0.06] focus:border-emerald-500/20")}',
'          ></textarea>',
'          <div className="absolute bottom-4 right-4 w-8 h-8">',
'            <svg className="w-8 h-8 -rotate-90" viewBox="0 0 36 36">',
'              <circle cx="18" cy="18" r="15" fill="none" stroke="rgba(255,255,255,0.05)" strokeWidth="2"></circle>',
'              <circle cx="18" cy="18" r="15" fill="none" className="char-ring" stroke={charPercent > 90 ? "#f87171" : (isLight ? "#fbbf24" : "#34d399")} strokeWidth="2" strokeDasharray="94.2" strokeDashoffset={94.2 - (94.2 * charPercent / 100)} strokeLinecap="round"></circle>',
'            </svg>',
'            <span className={"absolute inset-0 flex items-center justify-center text-[8px] " + (charPercent > 90 ? "text-red-400" : "text-gray-600")}>{2000 - text.length}</span>',
'          </div>',
'        </div>',
'',
'        <div className="h-4"></div>',
'',
'        <div className="fade-in mb-8" style={{animationDelay:"0.2s"}}>',
'          <p className="text-gray-500 text-xs mb-3 font-light">How does this feel? <span className="text-gray-600">(up to 3)</span></p>',
'          <div className="flex flex-wrap gap-2">',
'            {tagKeys.map(function(key) {',
'              var tag = tagData[key];',
'              var selected = selectedTags.indexOf(key) !== -1;',
'              return (',
'                <button key={key} onClick={function() { toggleTag(key); }}',
'                  className={"px-3.5 py-2 rounded-full text-xs transition-all duration-200 flex items-center gap-1.5 " + (selected ? (isLight ? "bg-amber-500/20 text-amber-300 border border-amber-500/30 shadow-lg shadow-amber-500/10" : "bg-emerald-500/20 text-emerald-300 border border-emerald-500/30 shadow-lg shadow-emerald-500/10") : "bg-white/[0.03] text-gray-500 border border-white/[0.06] hover:bg-white/[0.06] hover:text-gray-300")}',
'                ><span>{tag.emoji}</span><span>{tag.label}</span></button>',
'              );',
'            })}',
'          </div>',
'        </div>',
'',
'        {error && <p className="text-rose-400 text-sm text-center mb-4 bg-rose-500/10 border border-rose-500/20 rounded-xl py-2 px-4">{error}</p>}',
'',
'        <button onClick={handleSubmit} disabled={posting}',
'          className={"fade-in w-full py-4 rounded-2xl text-sm font-medium transition-all duration-300 " + (isLight ? "bg-gradient-to-r from-amber-500/20 to-amber-600/20 hover:from-amber-500/30 hover:to-amber-600/30 text-amber-300 border border-amber-500/25" : "bg-gradient-to-r from-emerald-500 to-emerald-400 hover:from-emerald-400 hover:to-emerald-300 text-black font-semibold shadow-lg shadow-emerald-500/20") + (posting ? " opacity-50" : " hover:shadow-xl hover:-translate-y-0.5")}',
'          style={{animationDelay:"0.25s"}}',
'        >{posting ? "Sending..." : (isLight ? "Share this light \\u2728" : "Send your letter \\u2709\\uFE0F")}</button>',
'',
'        <p className="fade-in text-gray-600 text-xs text-center mt-5 flex items-center justify-center gap-2" style={{animationDelay:"0.3s"}}>',
'          <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M16.5 10.5V6.75a4.5 4.5 0 1 0-9 0v3.75m-.75 11.25h10.5a2.25 2.25 0 0 0 2.25-2.25v-6.75a2.25 2.25 0 0 0-2.25-2.25H6.75a2.25 2.25 0 0 0-2.25 2.25v6.75a2.25 2.25 0 0 0 2.25 2.25Z" /></svg>',
'          Completely anonymous. No accounts. No tracking.',
'        </p>',
'      </div>',
'    </div>',
'  );',
'}'
].join('\n'));
console.log('2/3 WriteLetter.jsx upgraded');

fs.writeFileSync('client/src/components/LetterDetail.jsx', [
'import { useState, useEffect, useRef } from "react";',
'',
'var tagEmojis = { lonely: "\\uD83C\\uDF19", anxious: "\\u26A1", sad: "\\uD83C\\uDF27\\uFE0F", lost: "\\uD83C\\uDF0D", overwhelmed: "\\uD83C\\uDF0A", angry: "\\uD83D\\uDD25", numb: "\\uD83E\\uDDCA", grateful: "\\uD83D\\uDE4F", hopeful: "\\uD83C\\uDF31", healing: "\\uD83E\\uDE77" };',
'',
'export default function LetterDetail({ letterId, onBack }) {',
'  var [letter, setLetter] = useState(null);',
'  var [loading, setLoading] = useState(true);',
'  var [replyText, setReplyText] = useState("");',
'  var [replying, setReplying] = useState(false);',
'  var [error, setError] = useState("");',
'  var [hearted, setHearted] = useState(false);',
'  var bottomRef = useRef(null);',
'',
'  useEffect(function() {',
'    fetch("/api/letters/" + letterId).then(function(r) { return r.json(); }).then(function(data) { setLetter(data); setLoading(false); }).catch(function() { setLoading(false); });',
'  }, [letterId]);',
'',
'  function handleHeart() {',
'    setHearted(true);',
'    setTimeout(function() { setHearted(false); }, 600);',
'    fetch("/api/letters/" + letterId + "/heart", { method: "POST" }).then(function(r) { return r.json(); }).then(function(data) { setLetter(function(prev) { return Object.assign({}, prev, { hearts: data.hearts }); }); });',
'  }',
'',
'  function handleReply(e) {',
'    e.preventDefault();',
'    if (!replyText.trim() || replyText.trim().length < 2) { setError("Write at least a couple words."); return; }',
'    setReplying(true); setError("");',
'    fetch("/api/letters/" + letterId + "/reply", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ text: replyText.trim() }) })',
'      .then(function(r) { return r.json(); })',
'      .then(function(data) {',
'        if (data.error) { setError(data.error); } else {',
'          setLetter(function(prev) { return Object.assign({}, prev, { replies: (prev.replies || []).concat([data.reply]) }); });',
'          setReplyText("");',
'          setTimeout(function() { if (bottomRef.current) bottomRef.current.scrollIntoView({ behavior: "smooth" }); }, 100);',
'        }',
'        setReplying(false);',
'      }).catch(function() { setError("Something went wrong."); setReplying(false); });',
'  }',
'',
'  function timeAgo(ts) {',
'    var diff = Date.now() - ts; var mins = Math.floor(diff / 60000);',
'    if (mins < 1) return "just now"; if (mins < 60) return mins + "m ago";',
'    var hrs = Math.floor(mins / 60); if (hrs < 24) return hrs + "h ago";',
'    return Math.floor(hrs / 24) + "d ago";',
'  }',
'',
'  if (loading) return <div className="min-h-screen bg-[#0a0a0f] flex items-center justify-center"><p className="text-gray-500 text-sm">Opening letter...</p></div>;',
'  if (!letter) return <div className="min-h-screen bg-[#0a0a0f] flex flex-col items-center justify-center px-5"><p className="text-gray-400 mb-4">Letter not found.</p><button onClick={onBack} className="text-emerald-400 text-sm">{"\\u2190 Go back"}</button></div>;',
'',
'  var isLight = letter.type === "light";',
'  return (',
'    <div className="min-h-screen bg-[#0a0a0f] px-5 py-8">',
'      <style>{`',
'        @keyframes fadeInUp { from { opacity: 0; transform: translateY(20px); } to { opacity: 1; transform: translateY(0); } }',
'        @keyframes heartBeat { 0% { transform: scale(1); } 25% { transform: scale(1.3); } 50% { transform: scale(0.95); } 100% { transform: scale(1); } }',
'        @keyframes replySlide { from { opacity: 0; transform: translateX(-12px); } to { opacity: 1; transform: translateX(0); } }',
'        .fade-in { animation: fadeInUp 0.5s ease-out both; }',
'        .heart-beat { animation: heartBeat 0.5s ease-out; }',
'        .reply-card { animation: replySlide 0.4s ease-out both; }',
'      `}</style>',
'      <div className="max-w-xl mx-auto">',
'        <button onClick={onBack} className="fade-in text-gray-500 hover:text-white transition-colors text-sm mb-8 flex items-center gap-1">',
'          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M15 19l-7-7 7-7" /></svg>',
'          Back to letters',
'        </button>',
'',
'        <div className={"fade-in rounded-3xl p-7 sm:p-10 mb-8 relative overflow-hidden " + (isLight ? "bg-gradient-to-br from-amber-500/[0.05] to-amber-600/[0.02] border border-amber-500/[0.12]" : "bg-gradient-to-br from-white/[0.03] to-white/[0.01] border border-white/[0.06]")} style={{animationDelay:"0.1s"}}>',
'          <div className={"absolute top-4 right-6 text-6xl font-serif opacity-[0.04] select-none " + (isLight ? "text-amber-300" : "text-white")}>{"\\u201C"}</div>',
'          {isLight && <div className="flex items-center gap-2 mb-5"><span className="text-amber-400 text-sm">{"\\u2728"}</span><span className="text-amber-400/50 text-xs font-light tracking-widest uppercase">Wall of Light</span></div>}',
'          <p className={"text-lg sm:text-xl leading-relaxed mb-6 font-serif font-light relative z-10 " + (isLight ? "text-amber-100/90" : "text-gray-200")}>{letter.text}</p>',
'          {letter.tags && letter.tags.length > 0 && <div className="flex flex-wrap gap-1.5 mb-5">{letter.tags.map(function(tag) { return <span key={tag} className="text-[10px] text-emerald-400/50 bg-emerald-500/[0.06] px-2.5 py-1 rounded-full flex items-center gap-1"><span>{tagEmojis[tag] || ""}</span> {tag}</span>; })}</div>}',
'          <div className="flex items-center justify-between pt-4 border-t border-white/[0.04]">',
'            <span className="text-gray-600 text-xs">{timeAgo(letter.createdAt)}</span>',
'            <button onClick={handleHeart} className={"flex items-center gap-2 px-4 py-2 rounded-full transition-all duration-300 " + (hearted ? "bg-rose-500/20 text-rose-400" : "bg-white/[0.03] text-gray-500 hover:text-rose-400 hover:bg-rose-500/10")}>',
'              <span className={"text-base " + (hearted ? "heart-beat" : "")}>{"\\u2665"}</span>',
'              <span className="text-xs font-medium">{letter.hearts || 0}</span>',
'            </button>',
'          </div>',
'        </div>',
'',
'        <div className="fade-in mb-6" style={{animationDelay:"0.2s"}}>',
'          <h3 className="text-white text-sm font-medium mb-4">{(letter.replies || []).length > 0 ? "Replies (" + letter.replies.length + ")" : "No replies yet \\u2014 be the first"}</h3>',
'          <div className="space-y-3">',
'            {(letter.replies || []).map(function(reply, i) {',
'              return (',
'                <div key={reply.id} className="reply-card bg-emerald-500/[0.03] border border-emerald-500/[0.08] rounded-2xl px-5 py-4 hover:bg-emerald-500/[0.06] transition-colors" style={{animationDelay: (i * 0.1) + "s"}}>',
'                  <p className="text-gray-300 text-sm leading-relaxed">{reply.text}</p>',
'                  <span className="text-gray-600 text-xs mt-2 block">{timeAgo(reply.createdAt)}</span>',
'                </div>',
'              );',
'            })}',
'          </div>',
'          <div ref={bottomRef}></div>',
'        </div>',
'',
'        <form onSubmit={handleReply} className="fade-in border-t border-white/[0.06] pt-5" style={{animationDelay:"0.3s"}}>',
'          <p className="text-gray-500 text-xs mb-3 font-light">Reply with kindness</p>',
'          <div className="flex gap-3">',
'            <input type="text" value={replyText} onChange={function(e) { setReplyText(e.target.value); }} placeholder="You\\\'re not alone in this..." maxLength={500} className="flex-1 bg-white/[0.03] border border-white/[0.06] rounded-xl px-4 py-3 text-white text-sm placeholder-gray-600/50 focus:outline-none focus:border-emerald-500/20 transition-all" />',
'            <button type="submit" disabled={replying || !replyText.trim()} className="bg-emerald-500/20 hover:bg-emerald-500/30 text-emerald-400 rounded-xl px-5 py-3 text-sm font-medium transition-all disabled:opacity-30 hover:-translate-y-0.5">{replying ? "..." : "Send"}</button>',
'          </div>',
'          {error && <p className="text-red-400 text-xs mt-2">{error}</p>}',
'        </form>',
'      </div>',
'    </div>',
'  );',
'}'
].join('\n'));
console.log('3/3 LetterDetail.jsx upgraded');
console.log('\nDONE! All 3 components upgraded.');
console.log('Deploy: git add . && git commit -m "Upgrade Letters UI" && git push origin main');
